name: cart ci
on: [push,workflow_dispatch]
jobs: 
  call-common-workflow:
    uses: Thippareddygari/github-actions-reusable/.github/workflows/ci.yaml@main
  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout repository code
  #       uses: actions/checkout@v4
  #     - run: echo Build
  # Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout repository code
  #       uses: actions/checkout@v4
  #     - run: echo Tests

  # Deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout repository code
  #       uses: actions/checkout@v4
  #     - run: echo deploy